// version 1 of the taxonomy
export const taxonomy = {
    1: 'Arts & Entertainment',
    2: 'Arts & Entertainment/Acting & Theater',
    3: 'Arts & Entertainment/Comics',
    4: 'Arts & Entertainment/Concerts & Music Festivals',
    5: 'Arts & Entertainment/Dance',
    6: 'Arts & Entertainment/Entertainment Industry',
    7: 'Arts & Entertainment/Humor',
    8: 'Arts & Entertainment/Humor/Live Comedy',
    9: 'Arts & Entertainment/Live Sporting Events',
    10: 'Arts & Entertainment/Magic',
    11: 'Arts & Entertainment/Movie Listings & Theater Showtimes',
    12: 'Arts & Entertainment/Movies',
    13: 'Arts & Entertainment/Movies/Action & Adventure Films',
    14: 'Arts & Entertainment/Movies/Animated Films',
    15: 'Arts & Entertainment/Movies/Comedy Films',
    16: 'Arts & Entertainment/Movies/Cult & Indie Films',
    17: 'Arts & Entertainment/Movies/Documentary Films',
    18: 'Arts & Entertainment/Movies/Drama Films',
    19: 'Arts & Entertainment/Movies/Family Films',
    20: 'Arts & Entertainment/Movies/Horror Films',
    21: 'Arts & Entertainment/Movies/Romance Films',
    22: 'Arts & Entertainment/Movies/Thriller, Crime & Mystery Films',
    23: 'Arts & Entertainment/Music & Audio',
    24: 'Arts & Entertainment/Music & Audio/Blues',
    25: 'Arts & Entertainment/Music & Audio/Classical Music',
    26: 'Arts & Entertainment/Music & Audio/Country Music',
    27: 'Arts & Entertainment/Music & Audio/Dance & Electronic Music',
    28: 'Arts & Entertainment/Music & Audio/Folk & Traditional Music',
    29: 'Arts & Entertainment/Music & Audio/Jazz',
    30: 'Arts & Entertainment/Music & Audio/Musical Instruments',
    31: 'Arts & Entertainment/Music & Audio/Pop Music',
    32: 'Arts & Entertainment/Music & Audio/Rap & Hip-Hop',
    33: 'Arts & Entertainment/Music & Audio/Rock Music',
    34: 'Arts & Entertainment/Music & Audio/Rock Music/Classic Rock & Oldies',
    35: 'Arts & Entertainment/Music & Audio/Rock Music/Hard Rock & Progressive',
    36: 'Arts & Entertainment/Music & Audio/Rock Music/Indie & Alternative Music',
    37: 'Arts & Entertainment/Music & Audio/Soul & R&B',
    38: 'Arts & Entertainment/Music & Audio/Soundtracks',
    39: 'Arts & Entertainment/Music & Audio/Talk Radio',
    40: 'Arts & Entertainment/Music & Audio/World Music',
    41: 'Arts & Entertainment/Music & Audio/World Music/Reggae & Caribbean Music',
    42: 'Arts & Entertainment/Online Image Galleries',
    43: 'Arts & Entertainment/Online Video',
    44: 'Arts & Entertainment/Opera',
    45: 'Arts & Entertainment/TV Shows & Programs',
    46: 'Arts & Entertainment/TV Shows & Programs/TV Comedies',
    47: 'Arts & Entertainment/TV Shows & Programs/TV Documentary & Nonfiction',
    48: 'Arts & Entertainment/TV Shows & Programs/TV Dramas',
    49: 'Arts & Entertainment/TV Shows & Programs/TV Dramas/TV Soap Operas',
    50: 'Arts & Entertainment/TV Shows & Programs/TV Family-Oriented Shows',
    51: 'Arts & Entertainment/TV Shows & Programs/TV Reality Shows',
    52: 'Arts & Entertainment/TV Shows & Programs/TV Sci-Fi & Fantasy Shows',
    53: 'Arts & Entertainment/Visual Art & Design',
    54: 'Arts & Entertainment/Visual Art & Design/Design',
    55: 'Arts & Entertainment/Visual Art & Design/Painting',
    56: 'Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts',
    57: 'Autos & Vehicles',
    58: 'Autos & Vehicles/Cargo Trucks & Trailers',
    59: 'Autos & Vehicles/Classic Vehicles',
    60: 'Autos & Vehicles/Custom & Performance Vehicles',
    61: 'Autos & Vehicles/Gas Prices & Vehicle Fueling',
    62: 'Autos & Vehicles/Motor Vehicles (By Type)',
    63: 'Autos & Vehicles/Motor Vehicles (By Type)/Autonomous Vehicles',
    64: 'Autos & Vehicles/Motor Vehicles (By Type)/Convertibles',
    65: 'Autos & Vehicles/Motor Vehicles (By Type)/Coupes',
    66: 'Autos & Vehicles/Motor Vehicles (By Type)/Hatchbacks',
    67: 'Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles',
    68: 'Autos & Vehicles/Motor Vehicles (By Type)/Luxury Vehicles',
    69: 'Autos & Vehicles/Motor Vehicles (By Type)/Microcars & Subcompacts',
    70: 'Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles',
    71: 'Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles',
    72: 'Autos & Vehicles/Motor Vehicles (By Type)/Pickup Trucks',
    73: 'Autos & Vehicles/Motor Vehicles (By Type)/Scooters & Mopeds',
    74: 'Autos & Vehicles/Motor Vehicles (By Type)/Sedans',
    75: 'Autos & Vehicles/Motor Vehicles (By Type)/Station Wagons',
    76: 'Autos & Vehicles/Motor Vehicles (By Type)/SUVs & Crossovers',
    77: 'Autos & Vehicles/Motor Vehicles (By Type)/SUVs & Crossovers/Crossovers',
    78: 'Autos & Vehicles/Motor Vehicles (By Type)/Vans & Minivans',
    79: 'Autos & Vehicles/Towing & Roadside Assistance',
    80: 'Autos & Vehicles/Vehicle & Traffic Safety',
    81: 'Autos & Vehicles/Vehicle Parts & Accessories',
    82: 'Autos & Vehicles/Vehicle Repair & Maintenance',
    83: 'Autos & Vehicles/Vehicle Shopping',
    84: 'Autos & Vehicles/Vehicle Shopping/Used Vehicles',
    85: 'Autos & Vehicles/Vehicle Shows',
    86: 'Beauty & Fitness',
    87: 'Beauty & Fitness/Body Art',
    88: 'Beauty & Fitness/Face & Body Care',
    89: 'Beauty & Fitness/Face & Body Care/Antiperspirants, Deodorants & Body Sprays',
    90: 'Beauty & Fitness/Face & Body Care/Bath & Body Products',
    91: 'Beauty & Fitness/Face & Body Care/Clean Beauty',
    92: 'Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics',
    93: 'Beauty & Fitness/Face & Body Care/Nail Care Products',
    94: 'Beauty & Fitness/Face & Body Care/Perfumes & Fragrances',
    95: 'Beauty & Fitness/Face & Body Care/Razors & Shavers',
    96: 'Beauty & Fitness/Fashion & Style',
    97: 'Beauty & Fitness/Fitness',
    98: 'Beauty & Fitness/Fitness/Bodybuilding',
    99: 'Beauty & Fitness/Hair Care',
    100: 'Books & Literature',
    101: "Books & Literature/Children's Literature",
    102: 'Books & Literature/Poetry',
    103: 'Business & Industrial',
    104: 'Business & Industrial/Advertising & Marketing',
    105: 'Business & Industrial/Advertising & Marketing/Sales',
    106: 'Business & Industrial/Agriculture & Forestry',
    107: 'Business & Industrial/Agriculture & Forestry/Food Production',
    108: 'Business & Industrial/Automotive Industry',
    109: 'Business & Industrial/Aviation Industry',
    110: 'Business & Industrial/Business Operations',
    111: 'Business & Industrial/Business Operations/Flexible Work Arrangements',
    112: 'Business & Industrial/Business Operations/Human Resources',
    113: 'Business & Industrial/Commercial Lending',
    114: 'Business & Industrial/Construction & Maintenance',
    115: 'Business & Industrial/Construction & Maintenance/Civil Engineering',
    116: 'Business & Industrial/Defense Industry',
    117: 'Business & Industrial/Energy & Utilities',
    118: 'Business & Industrial/Energy & Utilities/Water Supply & Treatment',
    119: 'Business & Industrial/Hospitality Industry',
    120: 'Business & Industrial/Manufacturing',
    121: 'Business & Industrial/Metals & Mining',
    122: 'Business & Industrial/Pharmaceuticals & Biotech',
    123: 'Business & Industrial/Printing & Publishing',
    124: 'Business & Industrial/Retail Trade',
    125: 'Business & Industrial/Venture Capital',
    126: 'Computers & Electronics',
    127: 'Computers & Electronics/Antivirus & Malware',
    128: 'Computers & Electronics/Computer Peripherals',
    129: 'Computers & Electronics/Consumer Electronics',
    130: 'Computers & Electronics/Consumer Electronics/Cameras & Camcorders',
    131: 'Computers & Electronics/Consumer Electronics/Home Automation',
    132: 'Computers & Electronics/Consumer Electronics/Home Theater Systems',
    133: 'Computers & Electronics/Consumer Electronics/Wearable Technology',
    134: 'Computers & Electronics/Desktop Computers',
    135: 'Computers & Electronics/Laptops & Notebooks',
    136: 'Computers & Electronics/Network Security',
    137: 'Computers & Electronics/Networking',
    138: 'Computers & Electronics/Networking/Distributed & Cloud Computing',
    139: 'Computers & Electronics/Programming',
    140: 'Computers & Electronics/Software',
    141: 'Computers & Electronics/Software/Audio & Music Software',
    142: 'Computers & Electronics/Software/Desktop Publishing',
    143: 'Computers & Electronics/Software/Freeware & Shareware',
    144: 'Computers & Electronics/Software/Graphics & Animation Software',
    145: 'Computers & Electronics/Software/Operating Systems',
    146: 'Computers & Electronics/Software/Photo Software',
    147: 'Computers & Electronics/Software/Video Software',
    148: 'Computers & Electronics/Software/Web Browsers',
    149: 'Finance',
    150: 'Finance/Accounting & Auditing',
    151: 'Finance/Accounting & Auditing/Tax Preparation & Planning',
    152: 'Finance/Credit Cards',
    153: 'Finance/Financial Planning & Management',
    154: 'Finance/Financial Planning & Management/Retirement & Pension',
    155: 'Finance/Grants, Scholarships & Financial Aid',
    156: 'Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships',
    157: 'Finance/Home Financing',
    158: 'Finance/Insurance',
    159: 'Finance/Insurance/Auto Insurance',
    160: 'Finance/Insurance/Health Insurance',
    161: 'Finance/Insurance/Home Insurance',
    162: 'Finance/Insurance/Life Insurance',
    163: 'Finance/Insurance/Travel Insurance',
    164: 'Finance/Investing',
    165: 'Finance/Investing/Commodities & Futures Trading',
    166: 'Finance/Investing/Currencies & Foreign Exchange',
    167: 'Finance/Investing/Hedge Funds',
    168: 'Finance/Investing/Mutual Funds',
    169: 'Finance/Investing/Stocks & Bonds',
    170: 'Finance/Personal Loans',
    171: 'Finance/Student Loans & College Financing',
    172: 'Food & Drink',
    173: 'Food & Drink/Cooking & Recipes',
    174: 'Food & Drink/Cooking & Recipes/BBQ & Grilling',
    175: 'Food & Drink/Cooking & Recipes/Cuisines',
    176: 'Food & Drink/Cooking & Recipes/Cuisines/Vegetarian Cuisine',
    177: 'Food & Drink/Cooking & Recipes/Cuisines/Vegetarian Cuisine/Vegan Cuisine',
    178: 'Food & Drink/Cooking & Recipes/Healthy Eating',
    179: 'Food & Drink/Food & Grocery Retailers',
    180: 'Games',
    181: 'Games/Billiards',
    182: 'Games/Card Games',
    183: 'Games/Computer & Video Games',
    184: 'Games/Computer & Video Games/Action & Platform Games',
    185: 'Games/Computer & Video Games/Adventure Games',
    186: 'Games/Computer & Video Games/Casual Games',
    187: 'Games/Computer & Video Games/Competitive Video Gaming',
    188: 'Games/Computer & Video Games/Massively Multiplayer Games',
    189: 'Games/Computer & Video Games/Music & Dance Games',
    190: 'Games/Computer & Video Games/Simulation Games',
    191: 'Games/Computer & Video Games/Sports Games',
    192: 'Games/Computer & Video Games/Strategy Games',
    193: 'Games/Drawing & Coloring',
    194: 'Games/Roleplaying Games',
    195: 'Games/Table Tennis',
    196: 'Hobbies & Leisure',
    197: 'Hobbies & Leisure/Anniversaries',
    198: 'Hobbies & Leisure/Birthdays & Name Days',
    199: 'Hobbies & Leisure/Diving & Underwater Activities',
    200: 'Hobbies & Leisure/Fiber & Textile Arts',
    201: 'Hobbies & Leisure/Outdoors',
    202: 'Hobbies & Leisure/Outdoors/Fishing',
    203: 'Hobbies & Leisure/Outdoors/Hunting & Shooting',
    204: 'Hobbies & Leisure/Paintball',
    205: 'Hobbies & Leisure/Radio Control & Modeling',
    206: 'Hobbies & Leisure/Weddings',
    207: 'Home & Garden',
    208: 'Home & Garden/Gardening',
    209: 'Home & Garden/Home & Interior Decor',
    210: 'Home & Garden/Home Appliances',
    211: 'Home & Garden/Home Improvement',
    212: 'Home & Garden/Home Safety & Security',
    213: 'Home & Garden/Household Supplies',
    214: 'Home & Garden/Landscape Design',
    215: 'Internet & Telecom',
    216: 'Internet & Telecom/Email',
    217: 'Internet & Telecom/ISPs',
    218: 'Internet & Telecom/Phone Service Providers',
    219: 'Internet & Telecom/Search Engines',
    220: 'Internet & Telecom/Smart Phones',
    221: 'Internet & Telecom/Teleconferencing',
    222: 'Internet & Telecom/Text & Instant Messaging',
    223: 'Internet & Telecom/Web Apps & Online Tools',
    224: 'Internet & Telecom/Web Design & Development',
    225: 'Internet & Telecom/Web Hosting',
    226: 'Jobs & Education',
    227: 'Jobs & Education/Education',
    228: 'Jobs & Education/Education/Academic Conferences & Publications',
    229: 'Jobs & Education/Education/Colleges & Universities',
    230: 'Jobs & Education/Education/Distance Learning',
    231: 'Jobs & Education/Education/Early Childhood Education',
    232: 'Jobs & Education/Education/Early Childhood Education/Preschool',
    233: 'Jobs & Education/Education/Homeschooling',
    234: 'Jobs & Education/Education/Standardized & Admissions Tests',
    235: 'Jobs & Education/Education/Vocational & Continuing Education',
    236: 'Jobs & Education/Jobs',
    237: 'Jobs & Education/Jobs/Career Resources & Planning',
    238: 'Jobs & Education/Jobs/Job Listings',
    239: 'Law & Government',
    240: 'Law & Government/Crime & Justice',
    241: 'Law & Government/Legal',
    242: 'Law & Government/Legal/Legal Services',
    243: 'News',
    244: 'News/Economy News',
    245: 'News/Local News',
    246: 'News/Mergers & Acquisitions',
    247: 'News/Politics',
    248: 'News/Weather',
    249: 'News/World News',
    250: 'Online Communities',
    251: 'Online Communities/Dating & Personals',
    252: 'Online Communities/Forum & Chat Providers',
    253: 'Online Communities/Social Networks',
    254: 'People & Society',
    255: 'People & Society/Family & Relationships',
    256: 'People & Society/Family & Relationships/Ancestry & Genealogy',
    257: 'People & Society/Family & Relationships/Marriage',
    258: 'People & Society/Family & Relationships/Parenting',
    259: 'People & Society/Family & Relationships/Parenting/Adoption',
    260: 'People & Society/Family & Relationships/Parenting/Babies & Toddlers',
    261: 'People & Society/Family & Relationships/Parenting/Child Internet Safety',
    262: 'People & Society/Science Fiction & Fantasy',
    263: 'Pets & Animals',
    264: 'Pets & Animals/Pet Food & Pet Care Supplies',
    265: 'Pets & Animals/Pets',
    266: 'Pets & Animals/Pets/Birds',
    267: 'Pets & Animals/Pets/Cats',
    268: 'Pets & Animals/Pets/Dogs',
    269: 'Pets & Animals/Pets/Fish & Aquaria',
    270: 'Pets & Animals/Pets/Reptiles & Amphibians',
    271: 'Pets & Animals/Veterinarians',
    272: 'Real Estate',
    273: 'Real Estate/Lots & Land',
    274: 'Real Estate/Timeshares & Vacation Properties',
    275: 'Reference',
    276: 'Reference/Educational Resources',
    277: 'Reference/Foreign Language Study',
    278: 'Reference/How-To, DIY & Expert Content',
    279: 'Science',
    280: 'Science/Augmented & Virtual Reality',
    281: 'Science/Biological Sciences',
    282: 'Science/Biological Sciences/Genetics',
    283: 'Science/Chemistry',
    284: 'Science/Ecology & Environment',
    285: 'Science/Geology',
    286: 'Science/Machine Learning & Artificial Intelligence',
    287: 'Science/Physics',
    288: 'Science/Robotics',
    289: 'Shopping',
    290: 'Shopping/Antiques & Collectibles',
    291: "Shopping/Children's Clothing",
    292: 'Shopping/Consumer Resources',
    293: 'Shopping/Consumer Resources/Coupons & Discount Offers',
    294: 'Shopping/Costumes',
    295: 'Shopping/Flowers',
    296: "Shopping/Men's Clothing",
    297: 'Shopping/Party & Holiday Supplies',
    298: "Shopping/Women's Clothing",
    299: 'Sports',
    300: 'Sports/American Football',
    301: 'Sports/Australian Football',
    302: 'Sports/Auto Racing',
    303: 'Sports/Baseball',
    304: 'Sports/Basketball',
    305: 'Sports/Bowling',
    306: 'Sports/Boxing',
    307: 'Sports/Cheerleading',
    308: 'Sports/College Sports',
    309: 'Sports/Cricket',
    310: 'Sports/Cycling',
    311: 'Sports/Equestrian',
    312: 'Sports/Extreme Sports',
    313: 'Sports/Extreme Sports/Climbing & Mountaineering',
    314: 'Sports/Fantasy Sports',
    315: 'Sports/Golf',
    316: 'Sports/Gymnastics',
    317: 'Sports/Hockey',
    318: 'Sports/Ice Skating',
    319: 'Sports/Martial Arts',
    320: 'Sports/Motorcycle Racing',
    321: 'Sports/Olympics',
    322: 'Sports/Rugby',
    323: 'Sports/Running & Walking',
    324: 'Sports/Skiing & Snowboarding',
    325: 'Sports/Soccer',
    326: 'Sports/Surfing',
    327: 'Sports/Swimming',
    328: 'Sports/Tennis',
    329: 'Sports/Track & Field',
    330: 'Sports/Volleyball',
    331: 'Sports/Wrestling',
    332: 'Travel & Transportation',
    333: 'Travel & Transportation/Adventure Travel',
    334: 'Travel & Transportation/Air Travel',
    335: 'Travel & Transportation/Business Travel',
    336: 'Travel & Transportation/Car Rentals',
    337: 'Travel & Transportation/Cruises & Charters',
    338: 'Travel & Transportation/Family Travel',
    339: 'Travel & Transportation/Honeymoons & Romantic Getaways',
    340: 'Travel & Transportation/Hotels & Accommodations',
    341: 'Travel & Transportation/Long Distance Bus & Rail',
    342: 'Travel & Transportation/Low Cost & Last Minute Travel',
    343: 'Travel & Transportation/Luggage & Travel Accessories',
    344: 'Travel & Transportation/Tourist Destinations',
    345: 'Travel & Transportation/Tourist Destinations/Beaches & Islands',
    346: 'Travel & Transportation/Tourist Destinations/Regional Parks & Gardens',
    347: 'Travel & Transportation/Tourist Destinations/Theme Parks',
    348: 'Travel & Transportation/Tourist Destinations/Zoos, Aquariums & Preserves',
    349: 'Travel & Transportation/Travel Guides & Travelogues',
};

export const taxonomy_v2 = {
    1: '/Arts & Entertainment',
    350: '/Arts & Entertainment/Celebrities & Entertainment News',
    351: '/Arts & Entertainment/Comics & Animation',
    352: '/Arts & Entertainment/Events & Listings',
    353: '/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife',
    4: '/Arts & Entertainment/Events & Listings/Concerts & Music Festivals',
    354: '/Arts & Entertainment/Events & Listings/Event Ticket Sales',
    355: '/Arts & Entertainment/Events & Listings/Expos & Conventions',
    356: '/Arts & Entertainment/Events & Listings/Film Festivals',
    357: '/Arts & Entertainment/Events & Listings/Food & Beverage Events',
    9: '/Arts & Entertainment/Events & Listings/Live Sporting Events',
    12: '/Arts & Entertainment/Movies',
    13: '/Arts & Entertainment/Movies/Action & Adventure Films',
    15: '/Arts & Entertainment/Movies/Comedy Films',
    18: '/Arts & Entertainment/Movies/Drama Films',
    19: '/Arts & Entertainment/Movies/Family Films',
    20: '/Arts & Entertainment/Movies/Horror Films',
    21: '/Arts & Entertainment/Movies/Romance Films',
    358: '/Arts & Entertainment/Movies/Science Fiction & Fantasy Films',
    23: '/Arts & Entertainment/Music & Audio',
    24: '/Arts & Entertainment/Music & Audio/Blues',
    25: '/Arts & Entertainment/Music & Audio/Classical Music',
    26: '/Arts & Entertainment/Music & Audio/Country Music',
    27: '/Arts & Entertainment/Music & Audio/Dance & Electronic Music',
    359: '/Arts & Entertainment/Music & Audio/DJ Resources & Equipment',
    28: '/Arts & Entertainment/Music & Audio/Folk & Traditional Music',
    29: '/Arts & Entertainment/Music & Audio/Jazz',
    30: '/Arts & Entertainment/Music & Audio/Musical Instruments',
    31: '/Arts & Entertainment/Music & Audio/Pop Music',
    32: '/Arts & Entertainment/Music & Audio/Rap & Hip-Hop',
    33: '/Arts & Entertainment/Music & Audio/Rock Music',
    36: '/Arts & Entertainment/Music & Audio/Rock Music/Indie & Alternative Music',
    360: '/Arts & Entertainment/Music & Audio/Rock Music/Metal (Music)',
    361: '/Arts & Entertainment/Performing Arts',
    362: '/Arts & Entertainment/Performing Arts/Broadway & Musical Theater',
    363: '/Arts & Entertainment/TV & Video',
    364: '/Arts & Entertainment/TV & Video/Live Video Streaming',
    365: '/Arts & Entertainment/TV & Video/Movie & TV Streaming',
    46: '/Arts & Entertainment/TV & Video/TV Comedies',
    47: '/Arts & Entertainment/TV & Video/TV Documentary & Nonfiction',
    48: '/Arts & Entertainment/TV & Video/TV Dramas',
    50: '/Arts & Entertainment/TV & Video/TV Family-Oriented Shows',
    366: '/Arts & Entertainment/TV & Video/TV Game Shows',
    51: '/Arts & Entertainment/TV & Video/TV Reality Shows',
    52: '/Arts & Entertainment/TV & Video/TV Sci-Fi & Fantasy Shows',
    367: '/Arts & Entertainment/TV & Video/TV Talk Shows',
    53: '/Arts & Entertainment/Visual Art & Design',
    368: '/Arts & Entertainment/Visual Art & Design/Architecture',
    56: '/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts',
    57: '/Autos & Vehicles',
    369: '/Autos & Vehicles/Bicycles & Accessories',
    370: '/Autos & Vehicles/Boats & Watercraft',
    371: '/Autos & Vehicles/Campers & RVs',
    59: '/Autos & Vehicles/Classic Vehicles',
    372: '/Autos & Vehicles/Commercial Vehicles',
    60: '/Autos & Vehicles/Custom & Performance Vehicles',
    62: '/Autos & Vehicles/Motor Vehicles (By Type)',
    63: '/Autos & Vehicles/Motor Vehicles (By Type)/Autonomous Vehicles',
    373: '/Autos & Vehicles/Motor Vehicles (By Type)/Compact Cars',
    64: '/Autos & Vehicles/Motor Vehicles (By Type)/Convertibles',
    65: '/Autos & Vehicles/Motor Vehicles (By Type)/Coupes',
    374: '/Autos & Vehicles/Motor Vehicles (By Type)/Diesel Vehicles',
    66: '/Autos & Vehicles/Motor Vehicles (By Type)/Hatchbacks',
    67: '/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles',
    375: '/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles/Electric & Plug-In Vehicles',
    68: '/Autos & Vehicles/Motor Vehicles (By Type)/Luxury Vehicles',
    69: '/Autos & Vehicles/Motor Vehicles (By Type)/Microcars & Subcompacts',
    70: '/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles',
    71: '/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles',
    73: '/Autos & Vehicles/Motor Vehicles (By Type)/Scooters & Mopeds',
    74: '/Autos & Vehicles/Motor Vehicles (By Type)/Sedans',
    376: '/Autos & Vehicles/Motor Vehicles (By Type)/Sports Cars',
    75: '/Autos & Vehicles/Motor Vehicles (By Type)/Station Wagons',
    377: '/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs',
    72: '/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/Pickup Trucks',
    76: '/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/SUVs & Crossovers',
    78: '/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/Vans & Minivans',
    81: '/Autos & Vehicles/Vehicle Parts & Accessories',
    378: '/Autos & Vehicles/Vehicle Parts & Accessories/High Performance & Aftermarket Auto Parts',
    379: '/Autos & Vehicles/Vehicle Parts & Accessories/Vehicle Wheels & Tires',
    82: '/Autos & Vehicles/Vehicle Repair & Maintenance',
    83: '/Autos & Vehicles/Vehicle Shopping',
    84: '/Autos & Vehicles/Vehicle Shopping/Used Vehicles',
    86: '/Beauty & Fitness',
    380: '/Beauty & Fitness/Beauty Services & Spas',
    381: '/Beauty & Fitness/Beauty Services & Spas/Manicures & Pedicures',
    382: '/Beauty & Fitness/Cosmetology & Beauty Professionals',
    88: '/Beauty & Fitness/Face & Body Care',
    91: '/Beauty & Fitness/Face & Body Care/Clean Beauty',
    383: '/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries',
    89: '/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries/Antiperspirants, Deodorants & Body Sprays',
    384: '/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries/Feminine Hygiene Products',
    92: '/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics',
    94: '/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances',
    385: '/Beauty & Fitness/Face & Body Care/Skin & Nail Care',
    90: '/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Bath & Body Products',
    386: '/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Face Care Products',
    93: '/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Nail Care Products',
    387: '/Beauty & Fitness/Face & Body Care/Sun Care & Tanning Products',
    388: '/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal',
    95: '/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal/Razors & Shavers',
    96: '/Beauty & Fitness/Fashion & Style',
    97: '/Beauty & Fitness/Fitness',
    389: '/Beauty & Fitness/Fitness/Fitness Equipment & Accessories',
    390: '/Beauty & Fitness/Fitness/Fitness Equipment & Accessories/Fitness Technology Products',
    391: '/Beauty & Fitness/Fitness/Fitness Instruction & Personal Training',
    392: '/Beauty & Fitness/Fitness/Gyms & Health Clubs',
    393: '/Beauty & Fitness/Fitness/High Intensity Interval Training',
    394: '/Beauty & Fitness/Fitness/Yoga & Pilates',
    99: '/Beauty & Fitness/Hair Care',
    395: '/Beauty & Fitness/Hair Care/Shampoos & Conditioners',
    100: '/Books & Literature',
    396: '/Books & Literature/Audiobooks',
    397: '/Books & Literature/Book Retailers',
    101: "/Books & Literature/Children's Literature",
    398: '/Books & Literature/Fan Fiction',
    399: '/Books & Literature/Literary Classics',
    400: '/Books & Literature/Magazines',
    102: '/Books & Literature/Poetry',
    401: '/Books & Literature/Writers Resources',
    103: '/Business & Industrial',
    104: '/Business & Industrial/Advertising & Marketing',
    402: '/Business & Industrial/Building Materials & Supplies',
    403: '/Business & Industrial/Business Finance',
    113: '/Business & Industrial/Business Finance/Commercial Lending',
    404: '/Business & Industrial/Business Services',
    405: '/Business & Industrial/Business Services/Corporate Events',
    406: '/Business & Industrial/Business Services/Fire & Security Services',
    407: '/Business & Industrial/Business Services/Merchant Services & Payment Systems',
    408: '/Business & Industrial/Business Services/Office Supplies',
    409: '/Business & Industrial/Business Services/Office Supplies/Office Furniture',
    410: '/Business & Industrial/Business Services/Signage',
    411: '/Business & Industrial/Construction Consulting & Contracting',
    412: '/Business & Industrial/Document & Printing Services',
    413: '/Business & Industrial/Event Planning',
    414: '/Business & Industrial/Food Service',
    415: '/Business & Industrial/Industrial Materials & Equipment',
    416: '/Business & Industrial/Industrial Materials & Equipment/Work Safety Protective Gear',
    417: '/Business & Industrial/Moving & Relocation',
    418: '/Business & Industrial/Payroll Services',
    419: '/Business & Industrial/Recruitment & Staffing',
    126: '/Computers & Electronics',
    420: '/Computers & Electronics/Computer Hardware',
    421: '/Computers & Electronics/Computer Hardware/Computer Components',
    422: '/Computers & Electronics/Computer Hardware/Computer Drives & Storage',
    128: '/Computers & Electronics/Computer Hardware/Computer Peripherals',
    134: '/Computers & Electronics/Computer Hardware/Desktop Computers',
    135: '/Computers & Electronics/Computer Hardware/Laptops & Notebooks',
    423: '/Computers & Electronics/Computer Security',
    129: '/Computers & Electronics/Consumer Electronics',
    424: '/Computers & Electronics/Consumer Electronics/Audio Equipment',
    425: '/Computers & Electronics/Consumer Electronics/Audio Equipment/Headphones',
    426: '/Computers & Electronics/Consumer Electronics/Audio Equipment/Speakers',
    427: '/Computers & Electronics/Consumer Electronics/Audio Equipment/Stereo Systems & Components',
    428: '/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment',
    429: '/Computers & Electronics/Consumer Electronics/Car Audio',
    430: '/Computers & Electronics/Consumer Electronics/Gadgets & Portable Electronics',
    431: '/Computers & Electronics/Consumer Electronics/Game Systems & Consoles',
    432: '/Computers & Electronics/Consumer Electronics/Game Systems & Consoles/Handheld Game Consoles',
    131: '/Computers & Electronics/Consumer Electronics/Home Automation',
    132: '/Computers & Electronics/Consumer Electronics/Home Theater Systems',
    433: '/Computers & Electronics/Consumer Electronics/Televisions',
    434: '/Computers & Electronics/Electronics & Electrical',
    435: '/Computers & Electronics/Electronics & Electrical/Power Supplies',
    436: '/Computers & Electronics/Enterprise Technology',
    137: '/Computers & Electronics/Networking',
    437: '/Computers & Electronics/Networking/Network Monitoring & Management',
    438: '/Computers & Electronics/Networking/Networking Equipment',
    140: '/Computers & Electronics/Software',
    439: '/Computers & Electronics/Software/Business & Productivity Software',
    440: '/Computers & Electronics/Software/Business & Productivity Software/Accounting & Financial Software',
    441: '/Computers & Electronics/Software/Business & Productivity Software/Collaboration & Conferencing Software',
    442: '/Computers & Electronics/Software/Multimedia Software',
    141: '/Computers & Electronics/Software/Multimedia Software/Audio & Music Software',
    144: '/Computers & Electronics/Software/Multimedia Software/Graphics & Animation Software',
    443: '/Computers & Electronics/Software/Multimedia Software/Photo & Video Software',
    149: '/Finance',
    150: '/Finance/Accounting & Auditing',
    151: '/Finance/Accounting & Auditing/Tax Preparation & Planning',
    444: '/Finance/Banking',
    445: '/Finance/Banking/Debit & Checking Services',
    446: '/Finance/Banking/Savings Accounts',
    447: '/Finance/Credit & Lending',
    448: '/Finance/Credit & Lending/Auto Financing',
    152: '/Finance/Credit & Lending/Credit Cards',
    449: '/Finance/Credit & Lending/Credit Reporting & Monitoring',
    157: '/Finance/Credit & Lending/Home Financing',
    170: '/Finance/Credit & Lending/Personal Loans',
    171: '/Finance/Credit & Lending/Student Loans & College Financing',
    153: '/Finance/Financial Planning & Management',
    154: '/Finance/Financial Planning & Management/Retirement & Pension',
    158: '/Finance/Insurance',
    159: '/Finance/Insurance/Auto Insurance',
    160: '/Finance/Insurance/Health Insurance',
    161: '/Finance/Insurance/Home Insurance',
    162: '/Finance/Insurance/Life Insurance',
    163: '/Finance/Insurance/Travel Insurance',
    164: '/Finance/Investing',
    172: '/Food & Drink',
    173: '/Food & Drink/Cooking & Recipes',
    176: '/Food & Drink/Cooking & Recipes/Vegetarian Cuisine',
    177: '/Food & Drink/Cooking & Recipes/Vegetarian Cuisine/Vegan Cuisine',
    450: '/Food & Drink/Food',
    451: '/Food & Drink/Food/Baked Goods',
    452: '/Food & Drink/Food/Breakfast Foods',
    453: '/Food & Drink/Food/Candy & Sweets',
    454: '/Food & Drink/Food/Condiments & Dressings',
    455: '/Food & Drink/Food/Dairy & Eggs',
    456: '/Food & Drink/Food/Gourmet & Specialty Foods',
    457: '/Food & Drink/Food/Meat & Seafood',
    458: '/Food & Drink/Food/Meat & Seafood/Fish & Seafood',
    459: '/Food & Drink/Food/Organic & Natural Foods',
    460: '/Food & Drink/Grocery Delivery Services',
    461: '/Food & Drink/Restaurant Delivery Services',
    462: '/Food & Drink/Restaurants',
    463: '/Food & Drink/Restaurants/Fast Food',
    464: '/Food & Drink/Restaurants/Pizzerias',
    180: '/Games',
    465: '/Games/Board Games',
    183: '/Games/Computer & Video Games',
    184: '/Games/Computer & Video Games/Action & Platform Games',
    185: '/Games/Computer & Video Games/Adventure Games',
    186: '/Games/Computer & Video Games/Casual Games',
    187: '/Games/Computer & Video Games/Competitive Video Gaming',
    466: '/Games/Computer & Video Games/Driving & Racing Games',
    467: '/Games/Computer & Video Games/Shooter Games',
    191: '/Games/Computer & Video Games/Sports Games',
    192: '/Games/Computer & Video Games/Strategy Games',
    468: '/Games/Family-Oriented Games & Activities',
    194: '/Games/Roleplaying Games',
    196: '/Hobbies & Leisure',
    469: '/Hobbies & Leisure/Art & Craft Supplies',
    470: '/Hobbies & Leisure/Boating',
    471: '/Hobbies & Leisure/Holidays & Seasonal Events',
    201: '/Hobbies & Leisure/Outdoors',
    202: '/Hobbies & Leisure/Outdoors/Fishing',
    472: '/Hobbies & Leisure/Outdoors/Hiking & Camping',
    207: '/Home & Garden',
    473: '/Home & Garden/Bed & Bath',
    474: '/Home & Garden/Bed & Bath/Bathroom',
    475: '/Home & Garden/Bed & Bath/Bedroom',
    476: '/Home & Garden/Bed & Bath/Bedroom/Bedding & Bed Linens',
    477: '/Home & Garden/Bed & Bath/Bedroom/Beds & Headboards',
    478: '/Home & Garden/Bed & Bath/Bedroom/Mattresses',
    479: '/Home & Garden/Cleaning Services',
    209: '/Home & Garden/Home & Interior Decor',
    210: '/Home & Garden/Home Appliances',
    480: '/Home & Garden/Home Appliances/Vacuums & Floor Care',
    481: '/Home & Garden/Home Appliances/Water Filters & Purifiers',
    482: '/Home & Garden/Home Furnishings',
    483: '/Home & Garden/Home Furnishings/Countertops',
    484: '/Home & Garden/Home Furnishings/Curtains & Window Treatments',
    485: '/Home & Garden/Home Furnishings/Kitchen & Dining Furniture',
    486: '/Home & Garden/Home Furnishings/Lamps & Lighting',
    487: '/Home & Garden/Home Furnishings/Living Room Furniture',
    488: '/Home & Garden/Home Furnishings/Living Room Furniture/Sofas & Armchairs',
    489: '/Home & Garden/Home Furnishings/Outdoor Furniture',
    490: '/Home & Garden/Home Furnishings/Rugs & Carpets',
    211: '/Home & Garden/Home Improvement',
    491: '/Home & Garden/Home Improvement/Construction & Power Tools',
    492: '/Home & Garden/Home Improvement/Doors & Windows',
    493: '/Home & Garden/Home Improvement/Flooring',
    494: '/Home & Garden/Home Improvement/House Painting & Finishing',
    495: '/Home & Garden/Home Improvement/Locks & Locksmiths',
    496: '/Home & Garden/Home Improvement/Plumbing',
    497: '/Home & Garden/Home Improvement/Roofing',
    212: '/Home & Garden/Home Safety & Security',
    498: '/Home & Garden/Home Storage & Shelving',
    499: '/Home & Garden/Home Storage & Shelving/Cabinetry',
    500: '/Home & Garden/Home Swimming Pools, Saunas & Spas',
    213: '/Home & Garden/Household Supplies',
    501: '/Home & Garden/Household Supplies/Household Batteries',
    502: '/Home & Garden/Household Supplies/Household Cleaning Supplies',
    503: '/Home & Garden/HVAC & Climate Control',
    504: '/Home & Garden/HVAC & Climate Control/Air Conditioners',
    505: '/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves',
    506: '/Home & Garden/HVAC & Climate Control/Household Fans',
    507: '/Home & Garden/Kitchen & Dining',
    508: '/Home & Garden/Kitchen & Dining/Cookware & Diningware',
    509: '/Home & Garden/Kitchen & Dining/Cookware & Diningware/Cookware',
    510: '/Home & Garden/Kitchen & Dining/Cookware & Diningware/Diningware',
    511: '/Home & Garden/Kitchen & Dining/Dishwashers',
    512: '/Home & Garden/Kitchen & Dining/Microwaves',
    513: '/Home & Garden/Kitchen & Dining/Ranges, Cooktops & Ovens',
    514: '/Home & Garden/Kitchen & Dining/Refrigerators & Freezers',
    515: '/Home & Garden/Kitchen & Dining/Small Kitchen Appliances',
    516: '/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Blenders & Juicers',
    517: '/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Coffee & Espresso Makers',
    518: '/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Food Mixers',
    519: '/Home & Garden/Patio, Lawn & Garden',
    520: '/Home & Garden/Patio, Lawn & Garden/Barbecues & Grills',
    208: '/Home & Garden/Patio, Lawn & Garden/Gardening',
    214: '/Home & Garden/Patio, Lawn & Garden/Landscape Design',
    521: '/Home & Garden/Patio, Lawn & Garden/Yard Maintenance',
    522: '/Home & Garden/Patio, Lawn & Garden/Yard Maintenance/Lawn Mowers',
    523: '/Home & Garden/Pest Control',
    524: '/Home & Garden/Washers & Dryers',
    215: '/Internet & Telecom',
    525: '/Internet & Telecom/Communications Equipment',
    526: '/Internet & Telecom/Communications Equipment/Radio Equipment',
    527: '/Internet & Telecom/Mobile & Wireless Accessories',
    528: '/Internet & Telecom/Mobile Phones',
    529: '/Internet & Telecom/Mobile Phones/Mobile Phone Repair & Services',
    530: '/Internet & Telecom/Service Providers',
    531: '/Internet & Telecom/Service Providers/Cable & Satellite Providers',
    217: '/Internet & Telecom/Service Providers/ISPs',
    218: '/Internet & Telecom/Service Providers/Phone Service Providers',
    532: '/Internet & Telecom/Voice & Video Chat',
    533: '/Internet & Telecom/Web Services',
    534: '/Internet & Telecom/Web Services/Cloud Storage',
    535: '/Internet & Telecom/Web Services/Search Engine Optimization & Marketing',
    224: '/Internet & Telecom/Web Services/Web Design & Development',
    536: '/Internet & Telecom/Web Services/Web Hosting & Domain Registration',
    226: '/Jobs & Education',
    227: '/Jobs & Education/Education',
    537: '/Jobs & Education/Education/Business Education',
    229: '/Jobs & Education/Education/Colleges & Universities',
    538: '/Jobs & Education/Education/Computer Education',
    230: '/Jobs & Education/Education/Distance Learning',
    231: '/Jobs & Education/Education/Early Childhood Education',
    277: '/Jobs & Education/Education/Foreign Language Study',
    539: '/Jobs & Education/Education/Health Education & Medical Training',
    233: '/Jobs & Education/Education/Homeschooling',
    540: '/Jobs & Education/Education/Legal Education',
    541: '/Jobs & Education/Education/Open Online Courses',
    542: '/Jobs & Education/Education/Primary & Secondary Schooling (K-12)',
    543: '/Jobs & Education/Education/Private Tutoring Services',
    544: '/Jobs & Education/Education/School Supplies & Classroom Equipment',
    234: '/Jobs & Education/Education/Standardized & Admissions Tests',
    545: '/Jobs & Education/Education/Study Abroad',
    546: '/Jobs & Education/Education/Visual Arts & Design Education',
    547: '/Jobs & Education/Internships',
    236: '/Jobs & Education/Jobs',
    237: '/Jobs & Education/Jobs/Career Resources & Planning',
    238: '/Jobs & Education/Jobs/Job Listings',
    548: '/Jobs & Education/Jobs/Job Listings/Accounting & Finance Jobs',
    549: '/Jobs & Education/Jobs/Job Listings/Clerical & Administrative Jobs',
    550: '/Jobs & Education/Jobs/Job Listings/Education Jobs',
    551: '/Jobs & Education/Jobs/Job Listings/Executive & Management Jobs',
    552: '/Jobs & Education/Jobs/Job Listings/Government & Public Sector Jobs',
    553: '/Jobs & Education/Jobs/Job Listings/Health & Medical Jobs',
    554: '/Jobs & Education/Jobs/Job Listings/IT & Technical Jobs',
    555: '/Jobs & Education/Jobs/Job Listings/Legal Jobs',
    556: '/Jobs & Education/Jobs/Job Listings/Retail Jobs',
    557: '/Jobs & Education/Jobs/Job Listings/Sales & Marketing Jobs',
    558: '/Jobs & Education/Jobs/Job Listings/Temporary & Seasonal Jobs',
    559: '/Jobs & Education/Jobs/Resumes & Portfolios',
    239: '/Law & Government',
    560: '/Law & Government/Labor & Employment Law',
    242: '/Law & Government/Legal Services',
    243: '/News',
    561: '/News/Business News',
    245: '/News/Local News',
    247: '/News/Politics',
    249: '/News/World News',
    250: '/Online Communities',
    253: '/Online Communities/Social Networks',
    254: '/People & Society',
    562: '/People & Society/Charity & Philanthropy',
    258: '/People & Society/Parenting',
    259: '/People & Society/Parenting/Adoption',
    260: '/People & Society/Parenting/Babies & Toddlers',
    563: '/People & Society/Parenting/Child Care',
    263: '/Pets & Animals',
    264: '/Pets & Animals/Pet Food & Pet Care Supplies',
    265: '/Pets & Animals/Pets',
    267: '/Pets & Animals/Pets/Cats',
    268: '/Pets & Animals/Pets/Dogs',
    272: '/Real Estate',
    564: '/Real Estate/Property Development',
    565: '/Real Estate/Real Estate Listings',
    566: '/Real Estate/Real Estate Listings/Commercial Properties',
    567: '/Real Estate/Real Estate Listings/Residential Rentals',
    568: '/Real Estate/Real Estate Listings/Residential Rentals/Furnished Rentals',
    569: '/Real Estate/Real Estate Listings/Residential Sales',
    570: '/Real Estate/Real Estate Services',
    571: '/Real Estate/Real Estate Services/Property Inspections & Appraisals',
    289: '/Shopping',
    572: '/Shopping/Apparel',
    573: '/Shopping/Apparel/Apparel Services',
    574: '/Shopping/Apparel/Athletic Apparel',
    575: '/Shopping/Apparel/Casual Apparel',
    576: '/Shopping/Apparel/Casual Apparel/T-Shirts',
    291: "/Shopping/Apparel/Children's Clothing",
    577: '/Shopping/Apparel/Clothing Accessories',
    578: '/Shopping/Apparel/Clothing Accessories/Gems & Jewelry',
    579: '/Shopping/Apparel/Clothing Accessories/Gems & Jewelry/Rings',
    580: '/Shopping/Apparel/Clothing Accessories/Handbags & Purses',
    581: '/Shopping/Apparel/Clothing Accessories/Socks & Hosiery',
    582: '/Shopping/Apparel/Clothing Accessories/Watches',
    294: '/Shopping/Apparel/Costumes',
    583: '/Shopping/Apparel/Eyewear',
    584: '/Shopping/Apparel/Eyewear/Sunglasses',
    585: '/Shopping/Apparel/Footwear',
    586: '/Shopping/Apparel/Footwear/Athletic Shoes',
    587: '/Shopping/Apparel/Footwear/Boots',
    588: '/Shopping/Apparel/Footwear/Casual Shoes',
    589: '/Shopping/Apparel/Formal Wear',
    590: '/Shopping/Apparel/Headwear',
    296: "/Shopping/Apparel/Men's Clothing",
    591: '/Shopping/Apparel/Outerwear',
    592: '/Shopping/Apparel/Pants & Shorts',
    593: '/Shopping/Apparel/Shirts & Tops',
    594: '/Shopping/Apparel/Sleepwear',
    595: '/Shopping/Apparel/Suits & Business Attire',
    596: '/Shopping/Apparel/Swimwear',
    597: '/Shopping/Apparel/Undergarments',
    598: '/Shopping/Apparel/Uniforms & Workwear',
    298: "/Shopping/Apparel/Women's Clothing",
    599: "/Shopping/Apparel/Women's Clothing/Dresses",
    600: "/Shopping/Apparel/Women's Clothing/Skirts",
    293: '/Shopping/Coupons & Discount Offers',
    601: '/Shopping/Gifts & Special Event Items',
    295: '/Shopping/Gifts & Special Event Items/Flowers',
    297: '/Shopping/Gifts & Special Event Items/Party & Holiday Supplies',
    602: '/Shopping/Luxury Goods',
    603: '/Shopping/Mass Merchants & Department Stores',
    604: '/Shopping/Photo & Video Services',
    605: '/Shopping/Photo & Video Services/Event & Studio Photography',
    606: '/Shopping/Photo & Video Services/Photo Printing Services',
    607: '/Shopping/Product Reviews & Price Comparisons',
    608: '/Shopping/Toys',
    299: '/Sports',
    300: '/Sports/American Football',
    301: '/Sports/Australian Football',
    303: '/Sports/Baseball',
    304: '/Sports/Basketball',
    609: '/Sports/Combat Sports',
    309: '/Sports/Cricket',
    310: '/Sports/Cycling',
    315: '/Sports/Golf',
    317: '/Sports/Hockey',
    610: '/Sports/Motor Sports',
    321: '/Sports/Olympics',
    322: '/Sports/Rugby',
    323: '/Sports/Running & Walking',
    325: '/Sports/Soccer',
    611: '/Sports/Sporting Goods',
    612: '/Sports/Sporting Goods/Baseball & Softball Equipment',
    613: '/Sports/Sporting Goods/Golf Equipment',
    614: '/Sports/Sporting Goods/Hockey Equipment',
    615: '/Sports/Sporting Goods/Skateboarding Equipment',
    616: '/Sports/Sporting Goods/Soccer Equipment',
    617: '/Sports/Sporting Goods/Squash & Racquetball Equipment',
    618: '/Sports/Sporting Goods/Water Sports Equipment',
    619: '/Sports/Sporting Goods/Winter Sports Equipment',
    328: '/Sports/Tennis',
    620: '/Sports/Water Sports',
    327: '/Sports/Water Sports/Swimming',
    621: '/Sports/Winter Sports',
    324: '/Sports/Winter Sports/Skiing & Snowboarding',
    332: '/Travel & Transportation',
    334: '/Travel & Transportation/Air Travel',
    345: '/Travel & Transportation/Beaches & Islands',
    335: '/Travel & Transportation/Business Travel',
    336: '/Travel & Transportation/Car Rentals',
    337: '/Travel & Transportation/Cruises & Charters',
    338: '/Travel & Transportation/Family Travel',
    340: '/Travel & Transportation/Hotels & Accommodations',
    622: '/Travel & Transportation/Hotels & Accommodations/Vacation Rentals & Short-Term Stays',
    341: '/Travel & Transportation/Long Distance Bus & Rail',
    343: '/Travel & Transportation/Luggage & Travel Accessories',
    623: '/Travel & Transportation/Luggage & Travel Accessories/Backpacks & Utility Bags',
    624: '/Travel & Transportation/Luxury Travel',
    625: '/Travel & Transportation/Mountain & Ski Resorts',
    626: '/Travel & Transportation/Travel Agencies & Services',
    627: '/Travel & Transportation/Travel Agencies & Services/Guided Tours & Escorted Vacations',
    628: '/Travel & Transportation/Travel Agencies & Services/Sightseeing Tours',
    629: '/Travel & Transportation/Travel Agencies & Services/Vacation Offers',
};
